"""auto users

Revision ID: 146dacb020cf
Revises: 3c0902617af5
Create Date: 2022-01-29 23:32:56.011390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146dacb020cf'
down_revision = '3c0902617af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
